name: znacom
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.10+1
  modal_bottom_sheet: ^3.0.0
  toggle_switch: ^2.3.0
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/
  - assets/icon/
